language: c

arch:
      - AMD64
      - ppc64le

branches:
    only:
      - master

sudo: required

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tcl-tk; fi

script:
  - autoreconf -vi
  - if test -f .travis/configure-"$TRAVIS_OS_NAME"; then sh ./.travis/configure-"$TRAVIS_OS_NAME"; else sh ./configure; fi
  - make
  - sudo make install
